version: '3'
services:
  nginx:
    container_name: webserver
    # build from Dockerfile
    build: .
    # publish http and https ports
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # site config
      - ./nginx/<-->.conf:/etc/nginx/conf.d/<-->.conf
      # nginx config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # phpinfo 
      - ./html/index.php:/var/www/index.php
      # ssls
      - ./certbot/:/etc/letsencrypt
      # link containers
    depends_on:
      - php-fpm
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 12h && nginx -s reload --post-hook certbot -q renew; done;'

  php-fpm:
    container_name: php-fpm
    image: php:7.4-fpm
    ports:
     - "9000:9000"
    volumes:
     # custom www.conf
     - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
     - ./html/index.php:/var/www/index.php
